### ISSUE TITLE
I have a question about the format of annotation.

### ISSUE THREAD

**Issue by 2gunsu** [LulinPollux/yolov3-pytorch#2]
Hello. Thank you for sharing such a great project.
I am now trying to train with a custom dataset.
Is the format of the bbox in the txt file (Relative X center, Relative Y center, Relative W, Relative H) correct?

**Comment by synml** [comment]
Hello.
Yes, it's correct.
Thanks.

**Comment by 2gunsu** [comment]
Thanks for the quick response! 
Have a nice day.
